### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by AnasIbrahim** [swtyree/hope-dataset#3]
Hi,

I'm using the dataset for evaluation in a paper I will submit soon. Is there any associated paper with the dataset or something I can cite?

**Comment by Uio96** [comment]
> I'm using the dataset for evaluation in a paper I will submit soon. Is there any associated paper with the dataset or something I can cite?

Thanks for your interest in the dataset. 

For hope-dataset, you can refer to 

Tyree, S., Tremblay, J., To, T., Cheng, J., Mossier, T., & Birchfield, S. (2019). 6-DoF pose estimation of household objects for robotic manipulation: An accessible dataset and benchmark. In ICCV Workshop on Recovering 6D Object Pose.

For hope-video, 

Lin, Y., Tremblay, J., Tyree, S., Vela, P. A., & Birchfield, S. (2021, March). Multi-view Fusion for Multi-level Robotic Scene Understanding. In 2021 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS) (pp. 6817-6824). IEEE.

**Comment by swtyree** [comment]
Hi, thanks @Uio96 for replying. I just added bibtex entries to the readme with citations for both datasets. We have a new citation for HOPE-Image: 
```
@inproceedings{tyree2022hope,
  author={Tyree, Stephen and Tremblay, Jonathan and To, Thang and Cheng, Jia and Mosier, Terry and Smith, Jeffrey and Birchfield, Stan},
  title={6-DoF Pose Estimation of Household Objects for Robotic Manipulation: An Accessible Dataset and Benchmark},
  booktitle={arXiv preprint arXiv:2203.05701},
  year={2022}
}
```
