### ISSUE TITLE
Pre-trained Weights for CosyPose

### ISSUE THREAD

**Issue by Jing-lun** [swtyree/hope-dataset#4]
Hi @swtyree, I was wondering if the pre-trained weights for cosypose are going to be released as you mentioned in your paper?

https://arxiv.org/pdf/2203.05701.pdf

**Comment by swtyree** [comment]
Hi @Jing-lun , I'm sorry for the long delay in replying. Here is a link to the CosyPose weights for HOPE: https://drive.google.com/file/d/17H_RR2l6tJerofpBqkl7FtZYaGL4xPmF/view?usp=sharing. These weights are trained using the BOP meshes (https://bop.felk.cvut.cz/media/data/bop_datasets/hope_models.zip), which define object-centric coordinate system differently than this repository. If needed, I can find the transform between the two coordinates.
