### ISSUE TITLE
Follow your paper to make a new dataset

### ISSUE THREAD

**Issue by lyltc1** [swtyree/hope-dataset#5]
I want to follow your paper or similar paper to make a new datasets, from scanning to take pictures and annotate
pose. Can you show me some tools or code please? Thank you!

**Comment by swtyree** [comment]
Hi @lyltc1, we used a couple of custom tools for annotation. Our primary tool operated by solving for pose using correspondences between the object mesh and the 2.5D RGB-D point cloud. 
![tool_depth_left_sm](https://user-images.githubusercontent.com/12969365/178780871-8f87b7a4-86d5-470e-bd51-a9f0a4a5b547.jpg)
![tool_depth_right_sm](https://user-images.githubusercontent.com/12969365/178780889-e7cae1c1-cfaf-42c7-a13c-7d0b02afa42c.jpg)

Another tool did the same using PnP and correspondences between the mesh and the image.
![tool_pnp_sm](https://user-images.githubusercontent.com/12969365/178780932-afac607a-440a-4d25-bae1-fa3fe47e501b.jpg)

We also had another tool for "nudging" the translation/rotation by small amounts for a better visual alignment.
![tool_preview_2_sm](https://user-images.githubusercontent.com/12969365/178780973-6dcbd23d-a0ef-426a-89b8-cb1df8f9ff13.jpg)

I'll see if I can clean up the code and attach it here. The code may or may not work out of the box, but it should give you a starting point.

**Comment by swtyree** [comment]
Hi @lyltc1, I see that I never got that code cleaned up. In case an annotation tool is still useful to you (or someone else reading this issue), take a look at the code that we just released for creating the HANDAL dataset: https://github.com/NVlabs/HANDAL.
