### ISSUE TITLE
clarification on object-se

### ISSUE THREAD

**Issue by monajalal** [swtyree/hope-dataset#7]
Could you please clarify what is "TWO" here since there is only one barbecue sauce here

`[{"label": "barbecue-sauce", "TWO": [[0.5436763454963882, 0.622191933760276, -0.4349827125343375, 0.3578873048305161], [0.1073753759264946, 0.07318738847970963, 0.4580722153186798]]}]`

Also,

If there are two detected objects, why one has an array of size 4 and the other has an array of size 3?

Thanks
https://github.com/megapose6d/megapose6d/issues/19#issuecomment-1438980497

![image_rgb](https://user-images.githubusercontent.com/1892917/220442308-682ff2f8-646f-4b1f-b4ec-f5314bfe61f1.png)

**Comment by swtyree** [comment]
Hi @monajalal, I believe `TWO` is specific to CosyPose/MegaPose and not related to the HOPE dataset. Given that it's a length-4 vector and a length-3 vector, it might be a pose expressed as `[[quaternion], [translation]]`. But that's only a guess without looking at the code.
